Portal-Grup_EdaKok/Portal-Grup_EdaKok/Controllers/AddressController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Portal_Grup_EdaKok.Data;
using Portal_Grup_EdaKok.Interfaces;
using Portal_Grup_EdaKok.Models.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal_Grup_EdaKok.Controllers
{
    public class AddressController : Controller
    {
        public IActionResult Index()
        {
            List<Address> Addresss = _AddressRepo.GetItems();
            return View(Addresss);
        }

        private readonly ICustomer _customerRepo;
        private readonly IAddress _AddressRepo;
        private readonly PContext _context;

        public AddressController(IAddress Addressrepo, ICustomer customer)
        {

            _customerRepo = customer;
            _AddressRepo = Addressrepo;
        }
        public IActionResult Create()
        {
            Address Address = new Address();

          // ViewBag();
            return View(Address);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Address Address)
        {
            try
            {
                Address = _AddressRepo.Create(Address);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Details(int id)
        {
            Address Address = _AddressRepo.GetAddress(id);
            return View(Address);
        }
        public IActionResult Edit(int id)
        {
            Address Address = _AddressRepo.GetAddress(id);
            return View(Address);
        }
        [HttpPost]
        public IActionResult Edit(Address Address)
        {
            try
            {
                Address = _AddressRepo.Edit(Address);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            Address Address = _AddressRepo.GetAddress(id);
            return View(Address);
        }
        [HttpPost]
        public IActionResult Delete(Address Address)
        {
            try
            {
                Address = _AddressRepo.Delete(Address);


            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }



    }
}

Portal-Grup_EdaKok/Portal-Grup_EdaKok/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Portal_Grup_EdaKok.Data;
using Portal_Grup_EdaKok.Interfaces;
using Portal_Grup_EdaKok.Models.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal_Grup_EdaKok.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            List<Category> Categorys = _CategoryRepo.GetItems();
            return View(Categorys);
        }

        private readonly ICustomer _customerRepo;
        private readonly ICategory _CategoryRepo;
       

        public CategoryController(ICategory Categoryrepo, ICustomer customer)
        {

            _customerRepo = customer;
            _CategoryRepo = Categoryrepo;
        }
        public IActionResult Create()
        {
            Category Category = new Category();

          // ViewBag();
            return View(Category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category Category)
        {
            try
            {
                Category = _CategoryRepo.Create(Category);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Details(int id)
        {
            Category Category = _CategoryRepo.GetCategory(id);
            return View(Category);
        }
        public IActionResult Edit(int id)
        {
            Category Category = _CategoryRepo.GetCategory(id);
            return View(Category);
        }
        [HttpPost]
        public IActionResult Edit(Category Category)
        {
            try
            {
                Category = _CategoryRepo.Edit(Category);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            Category Category = _CategoryRepo.GetCategory(id);
            return View(Category);
        }
        [HttpPost]
        public IActionResult Delete(Category Category)
        {
            try
            {
                Category = _CategoryRepo.Delete(Category);


            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }



    }
}

Portal-Grup_EdaKok/Portal-Grup_EdaKok/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portal_Grup_EdaKok.Data;
using Portal_Grup_EdaKok.Interfaces;
using Portal_Grup_EdaKok.Models.Concrete;
using ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal_Grup_EdaKok.Controllers
{
    public class CustomerController : Controller
    {

        public IActionResult Index()
        {
            List<Customer> customers = _customerRepo.GetItems();
            return View(customers);
        }
        private readonly ICustomer _customerRepo;
        public CustomerController(ICustomer customerrepo)
        {
          
            _customerRepo = customerrepo;
        }
        public IActionResult Create()
        {
            Customer customer= new Customer();
            return View(customer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Customer customer)
        {
            try
            {

                customer = _customerRepo.Create(customer);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Details(int id)
        {
            Customer customer = _customerRepo.GetCustomer(id);
            return View(customer);
        }
        public IActionResult Edit(int id)
        {
            Customer customer = _customerRepo.GetCustomer(id);
            return View(customer);
        }
        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            try
            {
                customer = _customerRepo.Edit(customer);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            Customer customer = _customerRepo.GetCustomer(id);
            return View(customer);
        }
        [HttpPost]
        public IActionResult Delete(Customer customer)
        {
            try
            {
                customer = _customerRepo.Delete(customer);


            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
       
       
    }
}

Portal-Grup_EdaKok/Portal-Grup_EdaKok/Controllers/SKUController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portal_Grup_EdaKok.Data;
using Portal_Grup_EdaKok.Interfaces;
using Portal_Grup_EdaKok.Models.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal_Grup_EdaKok.Controllers
{
    public class SKUController : Controller
    {
        public IActionResult Index()
        {
            List<SKU> SKUs = _SKURepo.GetItems();
            return View(SKUs);
        }
        private readonly ISKU _SKURepo;
        public SKUController(ISKU SKUrepo)
        {
          
            _SKURepo = SKUrepo;
        }
        public IActionResult Create()
        {
            SKU SKU= new SKU();
            return View(SKU);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SKU SKU)
        {
            try
            {
                SKU = _SKURepo.Create(SKU);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Details(int id)
        {
            SKU SKU = _SKURepo.GetSKU(id);
            return View(SKU);
        }
        public IActionResult Edit(int id)
        {
            SKU SKU = _SKURepo.GetSKU(id);
            return View(SKU);
        }
        [HttpPost]
        public IActionResult Edit(SKU SKU)
        {
            try
            {
                SKU = _SKURepo.Edit(SKU);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            SKU SKU = _SKURepo.GetSKU(id);
            return View(SKU);
        }
        [HttpPost]
        public IActionResult Delete(SKU SKU)
        {
            try
            {
                SKU = _SKURepo.Delete(SKU);


            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }


       
    }
}

Portal-Grup_EdaKok/Portal-Grup_EdaKok/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portal_Grup_EdaKok</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portal_Grup_EdaKok</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Address" asp-action="Index">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SKU" asp-action="Index">Skus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderItem" asp-action="Index">OrderItems</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Portal_Grup_EdaKok - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>